export const ADD_TASK = 'ADD_TASK'
export const TASK_ADDED = 'TASK_ADDED'

export const DELETE_TASK = 'DELETE_TASK'
export const TASK_DELETED = 'TASK_DELETED'

export const LOAD_TASKS = 'LOAD_TASKS'
export const TASKS_LOADED = 'TASKS_LOADED'

export const LOGIN_USER = 'LOGIN_USER'
export const USER_LOGGEDIN = 'USER_LOGGEDIN'

export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT'

export const SET_ALERT = 'SET_ALERT'
export const RESET_ALERT = 'RESET_ALERT'

export const LOAD_USERS='LOAD_USERS'
export const USERS_LOADED='USERS_LOADED'

export const DELETE_USER='DELETE_USER'
export const USER_DELETED='USER_DELETED'

export const REGISTER_USER='REGISTER_USER'
export const USER_REGISTERED='USER_REGISTERED'

export const FETCH_WEATHER = 'FETCH_WEATHER'
export const WEATHER_FETCHED = 'WEATHER_FETCHED'

export const WEATHERLIST_FETCHED='WEATHERLIST_FETCHED'
export const FETCH_WEATHERLIST='FETCH_WEATHERLIST'

export const WEATHERDATELIST_FETCHED='WEATHERDATELIST_FETCHED'
export const FETCH_WEATHERDATELIST='FETCH_WEATHERDATELIST'